### ISSUE TITLE
Menu Bar (vertical) not hiding on touch devices

### ISSUE THREAD

**Issue by JBSoft** [flatsiedatsie/domoticz-aurora-theme#1]
When you push a button on the vertical menu bar on a tablet (for example), the menu bar is displaying all texts, which is correct, but is never hidind after that, except if you touch the screen again somewhere else.

I have absolutely no clue on how change that but I rise the point because it would be good to have this fixed.
Thanks for this already excellent work !

**Comment by pepeEL** [comment]
I have also the same problem on my tablet Galaxy Tab S

**Comment by flatsiedatsie** [comment]
This is because the menu is basically the vertical menu just being shown in a new way. It's difficult to change this.
