### ISSUE TITLE
No datavisualisation for certain weather sensors.

### ISSUE THREAD

**Issue by xztraz** [flatsiedatsie/domoticz-aurora-theme#14]
Wind chill and temp/hum from composite weather sensor(accurite 5in1 via RfLink) don't show any graphs.

![image](https://user-images.githubusercontent.com/25690871/36394981-0cc662f0-15b7-11e8-8bd9-f4ba021b79b4.png)

![image](https://user-images.githubusercontent.com/25690871/36395021-3513944e-15b7-11e8-99df-e27a90f3669a.png)

also rain and windspeed (from same sensor) don't seem to show any graph
![image](https://user-images.githubusercontent.com/25690871/36395059-64b25b04-15b7-11e8-9f06-eb64ebb7ad24.png)

**Comment by flatsiedatsie** [comment]
As the manual states, not all items currently have dataviz. Feel free to add this though. Look at the dataviz.js code. At the top you will see all the commands. Try adding one for yours, and then share the code with us?

**Comment by xztraz** [comment]
I will! i saw that after i filed this. :)

**Comment by xztraz** [comment]
I can't find a specific item for rain sensor or my temp/hum-combined sensor in html. wind is there but i can't get it to visualize. tried "ws", "any" as data source but nothing. 

temp/hum combined sensor
![image](https://user-images.githubusercontent.com/25690871/36538605-77af5148-17d4-11e8-8c3b-c9490ecbfec4.png)

Rain sensor(also from combined)
![image](https://user-images.githubusercontent.com/25690871/36538657-97a8e400-17d4-11e8-8173-0665b013743c.png)

Temp/hum sensor that works with dataviz (with item temp)
![image](https://user-images.githubusercontent.com/25690871/36538694-b5861952-17d4-11e8-9849-fddb7c1598da.png)

or am i doing it completely wrong :)

**Comment by xztraz** [comment]
listed stuff through json api instead. i guess the item-types should be from there but with small caps?

**Comment by xztraz** [comment]
I'm lost.. :D

**Comment by flatsiedatsie** [comment]
// listed stuff through json api instead. i guess the item-types should be from there but with small caps?

Spot on!

**Comment by flatsiedatsie** [comment]
I've added some code that will give items with the icecube icon an 'ice' class. That may help you target your sensor.

**Comment by xztraz** [comment]
sweet i'll have another try :)

**Comment by xztraz** [comment]
2 different temp sensors one with only temp/hum and one frome a weather station with multiple sensors. but temp/hum is one of them. if looking at json request for graph is the same but i can se in html output for the different sensors there is differences on the bstatus row

Working temp sensor (gives bg viz)
/json.htm?type=graph&sensor=temp&idx=98&range=day
html:
![image](https://user-images.githubusercontent.com/25690871/36597704-40209aee-18aa-11e8-9bd9-5b42a60cdfed.png)

weather station temp sensor (no bg viz) 
/json.htm?type=graph&sensor=temp&idx=108&range=day
html:
![image](https://user-images.githubusercontent.com/25690871/36597681-24638212-18aa-11e8-95ba-a5a60b90e903.png)

**Comment by flatsiedatsie** [comment]
1.
The aurora theme looks at the image that the element had, and uses that to give the element a CSS class. So a temperature icon -> "temp" class. Icecube icon -> "ice" class.

2.
The URL you posted tells us something important:
/json.htm?type=graph&sensor=**temp**&idx=98&range=day

Namely, that dDomoticz can show the dataviz in the same what that it does for temperature sensors.

So that has to go here:
generateDataviz($(this),"**temp**", "ba");


3.
Now for the last part of that call. Open this link in a new browser window:
[your domoticz base url here]/json.htm?type=graph&sensor=temp&idx=98&range=day

So for example:
192.168.1.10:8080/json.htm?type=graph&sensor=temp&idx=98&range=day

There you will see the raw data that Domoticz usually sends to its dataviz function. There you will be able to find the last piece of the puzzle.

You will see something like "te" or "v" or "any" as the name for the data that is not the timestamp data. take that as the second part of the call.

So put that here:
generateDataviz($(this),"**temp**", "**here**");

**Comment by xztraz** [comment]
Ah that last piece was what i got stuck on. Since there is allready a temp post i tought that should be enough and started looking for other clues. I'll try tonight.

**Comment by xztraz** [comment]
Non viz sensor (idx108)
![image](https://user-images.githubusercontent.com/25690871/36631850-0fb1f65c-197f-11e8-8d16-3758967b7850.png)

viz sensor(98)
![image](https://user-images.githubusercontent.com/25690871/36631860-29559618-197f-11e8-8e57-cef2756689fc.png)


both uses "te" wich is already in the js viz file.  hmmm..?

**Comment by xztraz** [comment]
Ah! Think i fond whats wrong!  Negtive values don't give you a viz!

**Comment by xztraz** [comment]
have another temp/hum sensor outside(sam model that gives viz) but this one is in negative temp range and viola no viz!

**Comment by xztraz** [comment]
Rain sensor

![image](https://user-images.githubusercontent.com/25690871/36631966-7ae04284-1980-11e8-9a47-010bade413d5.png)

This should work then

                $(this).find('.item.rain:not(.bandmember):not(:has(.dataviz))').each(function () {
                    $(this).addClass('hasdataviz');
                    generateDataviz($(this),"rain", "mm");
                });	

after cache cleanup  a viz graph!
awesome!

Just the issue with negative values to fix.
i'll add as many sensors as i can

**Comment by xztraz** [comment]
having some trouble with a visibility sensor:
in html
![image](https://user-images.githubusercontent.com/25690871/36632159-0c9398a0-1983-11e8-8e14-b3a16cc7466d.png)

tested this:
```
                $(this).find('.item.visibility:not(.bandmember):not(:has(.dataviz))').each(function () {
                    $(this).addClass('hasdataviz');
                    generateDataviz($(this),"counter", "v");
                });
```

json
![image](https://user-images.githubusercontent.com/25690871/36632171-4afff476-1983-11e8-8b82-c570001905d1.png)

not sure if item.visibility is right?  you say it looks at icon. should i look somwhere else?

**Comment by xztraz** [comment]
added wind and rain atleast in pull request.

**Comment by xztraz** [comment]
more mockups values and imgtype taken from dummy sensors. i get no graph for dummy sensors so not sure this works. 

```
                $(this).find('.item.air:not(.bandmember):not(:has(.dataviz))').each(function () {
                    $(this).addClass('hasdataviz');
                    generateDataviz($(this),"counter", "co2");
                }); 
                $(this).find('.item.speaker:not(.bandmember):not(:has(.dataviz))').each(function () {
                    $(this).addClass('hasdataviz');
                    generateDataviz($(this),"counter", "v");
                });
                $(this).find('.item.moisture:not(.bandmember):not(:has(.dataviz))').each(function () {
                    $(this).addClass('hasdataviz');
                    generateDataviz($(this),"counter", "v");
                });					$(this).find('.item.leaf:not(.bandmember):not(:has(.dataviz))').each(function () {
                    $(this).addClass('hasdataviz');
                    generateDataviz($(this),"temp", "hu");
                });
```

**Comment by xztraz** [comment]
Could the ice icon mess with neg values viz?

**Comment by flatsiedatsie** [comment]
I've added air, speaker, moisture and leaf classes. (See line 1358 in custom.js)

**Comment by xztraz** [comment]
thanks. added some more in custom.js.     gas and leaf moisture i can't get to work. leaf wetness don't seem to have a graph. gas i have no idea. should work. uncommentet those

**Comment by xztraz** [comment]
visibility, speaker, moist don't show month on viz. something missing for those

**Comment by xztraz** [comment]
ah different data values for month it seems. how do i solve this.  "any" maybe?
![image](https://user-images.githubusercontent.com/25690871/36646101-4f4b87f2-1a73-11e8-8d49-0d36d90e8a3c.png)

**Comment by xztraz** [comment]
no "any" does not work it takes every value. min,max,avg so you get a sawtooth pattern. hm. some other solution is needed

**Comment by xztraz** [comment]
I think this should be the last sensors. so close after pull and verify

**Comment by flatsiedatsie** [comment]
Thank you so much for your great work, I really appreciate it!

**Comment by flatsiedatsie** [comment]
I see you added a call to make dataviz on items with a "Waterflow" class. But that class is not yet added to the html.

If two sensortypes types use the same image, but require different dataviz calls (percent vs counter, for example), then the theme cannot currently handle that. Adding the classes based on the image is a bit of a hack after all.

So I suspect in these cases we have to make a choice which of the two sensor types is the one that gets the dataviz.

(Also, I try to keep classes all lowercase).

**Comment by xztraz** [comment]
Waterflow i found in the item class already for that item. used that to separate items seem to work. get graph on both items. i commented that ugly sollution at least :D

**Comment by xztraz** [comment]
water flow
![image](https://user-images.githubusercontent.com/25690871/36661213-0688aabe-1adb-11e8-86c6-892ff5caf500.png)
![image](https://user-images.githubusercontent.com/25690871/36661232-0f3d8bb6-1adb-11e8-992f-c6cccb3fd09e.png)

soil moisture
![image](https://user-images.githubusercontent.com/25690871/36661247-17d4724e-1adb-11e8-9f26-55f33dabbb63.png)
![image](https://user-images.githubusercontent.com/25690871/36661292-2c097bd8-1adb-11e8-9016-31ec67a2d2fd.png)

**Comment by xztraz** [comment]
could use SoilMoisture instead of generated moisture to really separate them

**Comment by xztraz** [comment]
This seem to work so i think we can close this? month bug in other issue
