### ISSUE TITLE
Rain sensor on dashboard combined with other sensors shows Mega meter!

### ISSUE THREAD

**Issue by xztraz** [flatsiedatsie/domoticz-aurora-theme#16]
![image](https://user-images.githubusercontent.com/25690871/36398511-c4a43568-15c7-11e8-8088-c1cbfb871acb.png)

**Comment by xztraz** [comment]
also windspeed M/S should be m/s i guess. :)

**Comment by flatsiedatsie** [comment]
The rain is in Mm, so it doesn't seem like the theme is capitalising things. Is it normal if you don't use the merge option?

**Comment by xztraz** [comment]
If not using merge this is what i get. so something makes it capitalize
![image](https://user-images.githubusercontent.com/25690871/36535869-5ea24506-17cb-11e8-94df-f74abc269aae.png)

**Comment by flatsiedatsie** [comment]
Found it. It was CSS capitalising things. I've removed that.

**Comment by xztraz** [comment]
Confirmed fixed.  Great! thanks!

![image](https://user-images.githubusercontent.com/25690871/36639717-145886c8-1a13-11e8-92d6-9cb4d64c0eeb.png)
