### ISSUE TITLE
new tab cam

### ISSUE THREAD

**Issue by xericcardo** [flatsiedatsie/domoticz-aurora-theme#17]
hello
I've been using aurora theme for some days now and I feel good.
Do you think it is possible to add a tab where you can insert an iframe link?
I would like to insert a page that I use for cameras with motioneye this would allow you to have a complete view of the house.
Thank you

**Comment by flatsiedatsie** [comment]
I've been thinking about something like this actually.

**Comment by xericcardo** [comment]
Good!!!
Grazie

**Comment by flatsiedatsie** [comment]
I've created this feature. Have a look in the Aurora thread on the forum.
