### ISSUE TITLE
Mobile and dashboard view at mobile devices

### ISSUE THREAD

**Issue by MiloshCZ** [flatsiedatsie/domoticz-aurora-theme#2]
Hi,
is it possible to change styles for mobile phones? Use current "Dashboard view" as "mobile view" and desktop (tablet) dashboard (with one column) as "Dashboard view"?
Current setup (mobile - dashboard view)
![Current mobile](https://user-images.githubusercontent.com/13035760/34776864-9699143c-f618-11e7-8962-051327a61efd.jpg) ![Current dashboard](https://user-images.githubusercontent.com/13035760/34776887-a870a1d4-f618-11e7-985b-542fe22c9a18.jpg)
New setup (mobile - dashboard)
![New mobile](https://user-images.githubusercontent.com/13035760/34776887-a870a1d4-f618-11e7-985b-542fe22c9a18.jpg) ![New dashboard](https://user-images.githubusercontent.com/13035760/34777121-9d14d87c-f619-11e7-8c2c-4737c031169b.jpg)

**Comment by flatsiedatsie** [comment]
No. Domoticz outputs this html. There is not much the theme can do about that. If you use the current version of the theme it does modify the look to better fit the rest of domoticz.
