### ISSUE TITLE
Theme settings button gone in Domoticz v 3.8946 (beta)

### ISSUE THREAD

**Issue by xztraz** [flatsiedatsie/domoticz-aurora-theme#20]
from forum:
https://www.domoticz.com/forum/viewtopic.php?f=8&t=20960&p=172589#p172589

Post  by Eoreh » Sunday 25 February 2018 15:10

Domoticz Version: 3.8946 
I update today to this version beta domoticz, and we lost button "Theme" in settings. I think cos. 
I also check in new version Aurora the same problem. 
Of course i clear all cache. 

EDIT: becouse jquery in domoticz upgrade to ->jquery-3.3.1.min.js
and from version jquery 3.0 .andSelf() removed, and we have to use .addBack()

![image](https://user-images.githubusercontent.com/25690871/36642673-5da4d3e2-1a43-11e8-92eb-de1fa2afc619.png)

**Comment by flatsiedatsie** [comment]
Thanks for the help!
