### ISSUE TITLE
dataviz for sensors with min,max,avg on month table dont work on month viz

### ISSUE THREAD

**Issue by xztraz** [flatsiedatsie/domoticz-aurora-theme#27]
Some sensors that have say

Day table
v
v
v

Month table
v_avg
v_min
v_max
and so on..

don't display any viz on month view.

![image](https://user-images.githubusercontent.com/25690871/36648901-24b532ce-1a99-11e8-83cb-c19744e388e8.png)
![image](https://user-images.githubusercontent.com/25690871/36648906-2d4ee6c8-1a99-11e8-9070-990ae8c6cc7a.png)
![image](https://user-images.githubusercontent.com/25690871/36646101-4f4b87f2-1a73-11e8-8d49-0d36d90e8a3c.png)

**Comment by flatsiedatsie** [comment]
I see you added a call to make dataviz on items with a "Waterflow" class. But that class is not yet added to the html.

If two sensortypes types use the same image, but require different dataviz calls (percent vs counter, for example), then the theme cannot currently handle that. Adding the classes based on the image is a bit of a hack after all.

So I suspect in these cases we have to make a choice which of the two sensor types is the one that gets the dataviz.

(Also, I try to keep classes all lowercase).

**Comment by xztraz** [comment]
List of sensors with (avg),min,max on month
Waterflow 
SoilMoisture(moisture)
Leafwetness(leaf)
scale
AudioLevel(speaker)
air
radiation
visibility

**Comment by xztraz** [comment]
i think a second datafield on each visualisation item is a nice solution. then script tht shows month takes second param instead. then avg values would show. i guess its the same amount of hacking to disable month for theese items

**Comment by flatsiedatsie** [comment]
Or just don't click/select on the month view?

**Comment by xztraz** [comment]
hehe. well. i just suggested some ways that it could be solved. but i get it. it's not that prioritized to fix :)
