### ISSUE TITLE
buttons on thermostat setpoint for up down odd behavior

### ISSUE THREAD

**Issue by xztraz** [flatsiedatsie/domoticz-aurora-theme#28]
if pushing the buttons for setpoint it adjust one degree up then not more. pushing down adjust down one degree. (ip opening popup you can adjust ok)

is this expected behavior or something a bit off? :)

![image](https://user-images.githubusercontent.com/25690871/36649653-1cfb7b3c-1a9f-11e8-9704-46f5a306f530.png)

**Comment by flatsiedatsie** [comment]
This is normal behaviour.

**Comment by xztraz** [comment]
ok so only adjustable by +-1 degree?  can't push beyond that on dashbox

**Comment by flatsiedatsie** [comment]
yes, kinda. It's just really slow.
