### ISSUE TITLE
Blinds device cannot be grouped

### ISSUE THREAD

**Issue by Tontze** [flatsiedatsie/domoticz-aurora-theme#30]
Tried to group bedroom lights, temperature and blinds together using "same name" method. This did not work, lights and temperature did merge, blinds stayed separate..
![blinds](https://user-images.githubusercontent.com/28216916/36922408-649fd986-1e70-11e8-8992-4b3b7a27e4d9.PNG)

**Comment by xztraz** [comment]
Only items with one icon and no sliders are supported for merge.

**Comment by Tontze** [comment]
Ok
