### ISSUE TITLE
One tile is different than others in desktop

### ISSUE THREAD

**Issue by Tontze** [flatsiedatsie/domoticz-aurora-theme#32]
for some reason, ulkolämpötila device is different than others ? 
![ulkolampo](https://user-images.githubusercontent.com/28216916/36922641-3d58a64a-1e71-11e8-90dc-cb454229819b.PNG)

**Comment by xztraz** [comment]
It should show big numbers in the box. Have you cleaned your cache

**Comment by Tontze** [comment]
I have, several times, and deleted app cache too. Background is also darker, and text too

**Comment by xztraz** [comment]
latest version of skin?

**Comment by Tontze** [comment]
Yes

**Comment by xztraz** [comment]
browser?

**Comment by Tontze** [comment]
Chrome

**Comment by xztraz** [comment]
are  you in compact view or something.?

looks like this for me in chrome
![image](https://user-images.githubusercontent.com/25690871/37055011-e69c9fc4-2180-11e8-9c28-66423149dd35.png)

**Comment by xztraz** [comment]
looks like cache is not clean or something. are you on beta on domoticz?

**Comment by Tontze** [comment]
I am in compact mode, because in normal mode sliders are missing and switches dont fit on screen at all ..
![sieppaa](https://user-images.githubusercontent.com/28216916/37056079-08627c68-218c-11e8-9447-d6ca7ebb1ad9.PNG)

I have deleted appcache (chrome://appcache-internals/#) and done F5,  CTRL+F5 and CTRL+R

Looks same in normal mode ?

**Comment by Tontze** [comment]
I did delete ulkolämpötila device, and added it newly, it didnt help. 
![sieppaa](https://user-images.githubusercontent.com/28216916/37134843-fd55149e-22a2-11e8-89a0-7df5b4fc2447.PNG)

**Comment by xztraz** [comment]
your devices page looks different from theme too.  i just clean cache, cookies and files in settings in the browser. 

Also compact mode is a bit wonky what i understand. you have the sliders in normal view too, just looks different

![image](https://user-images.githubusercontent.com/25690871/37163151-52c70136-22f7-11e8-9a23-afa1cf1dc5d5.png)

the thing that differs them are negative temp value and ice icon is applied from theme. i look at my sensors (not in compact mode) 
![image](https://user-images.githubusercontent.com/25690871/37163549-6260c8ba-22f8-11e8-893e-3add77b72b65.png)

**Comment by Tontze** [comment]
i reseted all settings, still there is size difference between light buttons, and between temperature sensors... 

![capture](https://user-images.githubusercontent.com/28216916/37364348-ea0973da-2702-11e8-83a4-ce4439f714f4.PNG)

**Comment by Tontze** [comment]
Oh, it looks like max big block is 3 ? if i swap makuuhuone and portaikko, makuuhuone comes big, and portaikko goes small ?

**Comment by xztraz** [comment]
yes thats a feature of the skin. 3 first items is larger.
