### ISSUE TITLE
Show three highlighted items

### ISSUE THREAD

**Issue by virusczz** [flatsiedatsie/domoticz-aurora-theme#34]
Hi, Super theme. I want to have more like 3 big items. I managed to have 9. Only i can not do the 9x highcharts to run. 
Can you implement the possibility to chose the number how many items to be Highlighted?

**Comment by virusczz** [comment]
![image](https://user-images.githubusercontent.com/36480973/37004758-ceb6a440-20d1-11e8-9a42-dc249eedea19.png)

**Comment by virusczz** [comment]
![image](https://user-images.githubusercontent.com/36480973/37005800-b9028b56-20d5-11e8-84a7-d42d3819d9e7.png)

Done :)  manualy: -n+3 changed to -n+9 in files:
dashboard_show_data_visualizations.js
dashboard_highlights_see-through.css

**Comment by virusczz** [comment]
What i don't know how to do is to add a box to write the number, and not to have only 3.

**Comment by xztraz** [comment]
other settings in theme is saved in user variables. you could start there. somewhere in code there should be something that reads from user vars. should be a case of mostly copy paste coding :)

**Comment by flatsiedatsie** [comment]
The best thing would be to create a setting where users enter a number. Then javascript could add a CSS class to that number of devices. Then the theme's CSS could be changed to just apply to thing with that tag, instead of the hardcoded first three devices. Perhaps in the future..

**Comment by flatsiedatsie** [comment]
There is now an option to make all items large. That will have to do for now.
