### ISSUE TITLE
No percentage shown when domoticz is updated on mobile device

### ISSUE THREAD

**Issue by TheReptile** [flatsiedatsie/domoticz-aurora-theme#35]
When I update domoticz on my mobile, everything works, but the percentage is missing.

**Comment by flatsiedatsie** [comment]
Can you test if you do see the percentage if you use the defaul theme?

**Comment by TheReptile** [comment]
Oops, sorry. Due to holidays I forgot about this.
To answer your question, no this doesn't happen with the default theme. 
I also noticed the same issue happens on the about screen.
