### ISSUE TITLE
Selected color scheme not applied to all tabs

### ISSUE THREAD

**Issue by mrohner** [flatsiedatsie/domoticz-aurora-theme#39]
Hi, I selected a middle blue as a background and white text. This appears correctly in all the Tabs (Switches, Scenes, Dashboard, Temerature etc.) but not in the Utility Tab where the text color is black instead of white.

**Comment by bennyente** [comment]
Hi. Same problem here.

**Comment by flatsiedatsie** [comment]
Thanks. Domoticz decided to hard-code the color in the CSS somehow. I've fixed it.
