### ISSUE TITLE
Bad formatting within a tile

### ISSUE THREAD

**Issue by mrohner** [flatsiedatsie/domoticz-aurora-theme#40]
![clipboard02](https://user-images.githubusercontent.com/15965653/43049747-45e6338a-8dfd-11e8-8e7d-d7dbce8edaf4.png)

This effect is randomly occuring. Normally the symbol and the data are on one line
This is within the dashboard. And what is the battery symbol doing there ?

**Comment by flatsiedatsie** [comment]
None of those merged devices has a battery?

Can you figure out what is causing the issue? Could it be the size of your browser window?

**Comment by mrohner** [comment]
None of these devices have a battery, although the Tasmota software I use for my devices do send battery information (for a reason I do not understand) to Domoticz.
2018-07-26 09:00:54.415 MQTT: Topic: domoticz/in, Message: {"idx":4,"nvalue":0,"svalue":"28.8;44.2;1","Battery":17,"RSSI":3}
This is probably the reason the battery symbol is displayed
