### ISSUE TITLE
All rooms within a combined tile listed even though just one room selected

### ISSUE THREAD

**Issue by mrohner** [flatsiedatsie/domoticz-aurora-theme#41]
In Dashboard all rooms within a combined tile listed even though just one room selected. See pic for living room. Tiles show all other rooms as well i.e. for Movement and Temperature
![clipboard03](https://user-images.githubusercontent.com/15965653/43064260-aee1b204-8e5e-11e8-8258-5de65cb25407.png)

**Comment by flatsiedatsie** [comment]
Unfortunately, the javascript code that merges devices doesn't check what room you have selected. There's not much I can do about this at the moment, as I don't remember seeing any data about rooms that I can easily hack into. Although.. the code could check if a device is visible before it merges them. And then you could re-call the entire merging code every time you select a new room. But that's quite a bit of hassle.
