### ISSUE TITLE
Icon size too big

### ISSUE THREAD

**Issue by mrohner** [flatsiedatsie/domoticz-aurora-theme#42]
See pic for Blinds dining
![clipboard04](https://user-images.githubusercontent.com/15965653/43065076-03b67d6c-8e61-11e8-91e4-947340308baf.png)

**Comment by flatsiedatsie** [comment]
Are you using normal or compact view?

**Comment by mrohner** [comment]
Hi, I use the dashboard in Normal mode

**Comment by flatsiedatsie** [comment]
I changed some CSS. Can you check if it fixes your issue?

**Comment by mrohner** [comment]
Thank you, but for the moment I switched back to the default Domoticz theme, I might check out aurora later in the year again. Good work by the way
