### ISSUE TITLE
New beta event editor

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#43]
The new beta contains an updated version of the event editor.
But the current version of aurora doesn't show that page correctly (see screenshot)

![image](https://user-images.githubusercontent.com/14561640/47452735-3f971900-d7cb-11e8-8a32-9a36438e70ad.png)

![image](https://user-images.githubusercontent.com/14561640/47452764-4887ea80-d7cb-11e8-9a1c-c70e286d6152.png)

So at this moment, you can't update events (scripts) with this theme

**Comment by flatsiedatsie** [comment]
I will look into this.

**Comment by galadril** [comment]
awesome!= thanks
