### ISSUE TITLE
Buttons don't work to jump to graphicz

### ISSUE THREAD

**Issue by Pandabeer40** [flatsiedatsie/domoticz-aurora-theme#44]
![image](https://user-images.githubusercontent.com/44602201/47705701-9d8e8b00-dc27-11e8-9230-4775b4dcfba9.png)

When i click on one of the icons in the past the graphs were shown - now nothing happens - some icons of the Weather still works (like rain, uv etc)
Is it possible to fix this (I work with latest beta of Domoticz on RPi - tried some browsers - every browser has the same issue (firefox, chrome etc)

Looks like the icons don't have the link to the graph when they get combined to one tile (due to the same name)

Thank you in advance,
Peter

**Comment by flatsiedatsie** [comment]
Thanks Peter. I've noticed it too. 

I remember building it in such a way what this issue could be avoided. The javascript is already attached to the icons before the merge starts, and I had to try and keep that attachment while moving things around. It seems something changed in Domoticz and it's now broken anyway.

**Comment by flatsiedatsie** [comment]
Should be fixed.
