### ISSUE TITLE
Html files are changed

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#52]
The html files for switches, scenes and utilities are changed in the latest beta:
https://github.com/domoticz/domoticz/commits/development

So now this theme looks like:
![afbeelding](https://user-images.githubusercontent.com/14561640/52328895-79de9c00-29f1-11e9-83fd-8a868c3503f1.png)

**Comment by galadril** [comment]
https://github.com/domoticz/domoticz/commit/5366c2f1f9da527beb636512f04be45b36c97ee4

**Comment by flatsiedatsie** [comment]
Thank you. I've merged your code.

**Comment by galadril** [comment]
Thanks
