### ISSUE TITLE
Wrong alignments on grouped items (and invisible icons)

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#54]
I have some wrong aligned grouped items:
![afbeelding](https://user-images.githubusercontent.com/14561640/56639307-add07180-6670-11e9-88ce-007639c6a2ba.png)

As you can see, also icons are invisible/not showing.
![afbeelding](https://user-images.githubusercontent.com/14561640/56639345-c2146e80-6670-11e9-8cb8-fe0452d94e51.png)

**Comment by flatsiedatsie** [comment]
Thanks.

In the first one I suspect too many items is the cause. In the second it's probably a problem with the wind having multiple lines.

I'm winding down support of the theme. I've personally moved on to using the Mozilla WebThings gateway.

**Comment by galadril** [comment]
ah too bad.. im not really a web dev.. more a mobile app builder

**Comment by galadril** [comment]
Was fixed after the pull request
