### ISSUE TITLE
Wrong alignment of Selectors (in the last beta)

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#56]
The allignment of selectors are off since the last domoticz beta due to this commit:
https://github.com/domoticz/domoticz/commit/0513720c8233d66d0c64bb6033427efd08a778de

![selector](https://user-images.githubusercontent.com/14561640/57617261-a79f2800-7580-11e9-8acf-a448e7adb86e.png)

**Comment by galadril** [comment]
Have you seen my pull request to fix this matter? small fix

**Comment by flatsiedatsie** [comment]
Thank you for the great work! I've accepted the change.

I haven't tested it, so I'm trusting you here.
