### ISSUE TITLE
Dashboard icon issue with Blinds that support Stop buttons

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#59]
There is an issue with blinds that support a Stop button, see screenshot:

![dashboard](https://user-images.githubusercontent.com/14561640/62109149-fcaf2800-b2ab-11e9-95a7-024688b65714.png)

**Comment by flatsiedatsie** [comment]
Thanks for reporting, but I'm no longer supporting this theme. If you create a pull request I will happily add it though.

**Comment by galadril** [comment]
Yeah I know.. I'm just writing the bugs down.. For when I or sombody else
has time..

Op di 30 jul. 2019 15:40 schreef flatsiedatsie <notifications@github.com>:

**Comment by flatsiedatsie** [comment]
This should be fixed now. Could you confirm?

**Comment by galadril** [comment]
ill test tonight!

**Comment by galadril** [comment]
Sorry for the late notice, but i've tested all different blind types and they look great!

![afbeelding](https://user-images.githubusercontent.com/14561640/64256428-c48eab00-cf23-11e9-94ae-90e1e17d7070.png)
