### ISSUE TITLE
New Dialog on Room plan (Adding devices to a room)

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#62]
Domoticz added a new dialog for adding devices to a room, which is not themed at the moment

![afbeelding](https://user-images.githubusercontent.com/14561640/74815753-196b8580-52fa-11ea-9aa6-7828c1816422.png)

**Comment by M-M3on** [comment]
Fixed and optimized with pullrequest #71 
![image](https://user-images.githubusercontent.com/33467332/99149923-5ac67100-2691-11eb-8724-685ea0e295e5.png)

**Comment by galadril** [comment]
awesome!
