### ISSUE TITLE
Camera Preview in the new domoticz v2020.1 

### ISSUE THREAD

**Issue by mobielbas** [flatsiedatsie/domoticz-aurora-theme#64]
Since i have updated my Domoticz to version 2020.1 i don't have the preview of the camera anymore in my Aurora Theme? Does someone have the same issue?

**Comment by TheMaxNL** [comment]
Still working, but the camera screen high size is to narrow. Where can I change that?

**Comment by Nancyn26** [comment]
Same problem. Preview is not showing up anymore since updating to 2020.1.

**Comment by flatsiedatsie** [comment]
Sorry, but this theme is not longer under support. If someone creates a fix I will happily accept it, but I won't create it. I have moved from Domoticz to the Mozilla WebThings Gateway.
