### ISSUE TITLE
Theme manager

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#65]
Hi

I just wanted to let you know, that people can install and auto update this theme in Domoticz via the Domoticz Theme Manager (Python plugin)
https://github.com/galadril/domoticz-theme-manager

Can you maybe add this info to the Readme??

Mark

**Comment by flatsiedatsie** [comment]
Sure, no problem.

**Comment by galadril** [comment]
Sweet, thanks
