### ISSUE TITLE
Missing spaces in mobile view

### ISSUE THREAD

**Issue by MiloshCZ** [flatsiedatsie/domoticz-aurora-theme#7]
Hi,
there are missing spaces in mobile view for Temperature + humidity sensors:
![mobile](https://user-images.githubusercontent.com/13035760/35088884-7855bc28-fc35-11e7-80ac-ce77b95f00e5.png)
I think, that better is: "0.6°C 91%" (no space between number and unit)

**Comment by flatsiedatsie** [comment]
I've created a quick fix for this.
