### ISSUE TITLE
Aurora broken on the latest beta of Domoticz?

### ISSUE THREAD

**Issue by galadril** [flatsiedatsie/domoticz-aurora-theme#75]
It looks like this theme just broke on the latest Domoticz update.
![image](https://user-images.githubusercontent.com/14561640/135722172-d14c92e0-d3cc-4412-ac85-a9a8db23263f.png)

Domoticz version 2021.1 (build 13670)

Probably because of lots of web/angular updates last couple of days >>
https://github.com/domoticz/domoticz/commits/development

**Comment by cronyx** [comment]
Same problem, I had roll back the domoticz version to 13653 :(

**Comment by cronyx** [comment]
as a dirty fix -  replace all 'acttheme' to 'styles/aurora' in aurora/custom.js

**Comment by nico21311** [comment]
Thanks for the fix, it is not perfect but better than before

**Comment by galadril** [comment]
Made a PR for this suggested change

**Comment by GravityRZ** [comment]
so is this theme not supported anymore with latest beta

**Comment by flatsiedatsie** [comment]
Apparently if you call the theme 'aurora' it should work.
