### ISSUE TITLE
Low batt issue

### ISSUE THREAD

**Issue by JBSoft** [flatsiedatsie/domoticz-aurora-theme#8]
Hello,

I had a low batt on a sensor today, and I discovered two things:
1- The yellow is not really obvious: I prefer if I can identify the sensor very easily, and it is not the case here.
2- The battery display shows a "ghost" status in addition of the main one. don't know if it is on purpose...
![image](https://user-images.githubusercontent.com/20253547/35099848-ce8e1288-fc59-11e7-961c-8b03d6a76369.png)

**Comment by flatsiedatsie** [comment]
Fixed.
